language: erlang

env:
  - LUA=""
  - LUA="luajit"

branches:
  only:
    - master

install:
  - sudo apt-get install luajit luarocks
  - sudo luarocks install luafilesystem
  - sudo luarocks install busted

script: "busted spec"
