language: erlang
env:
- LUA=""
- LUA="luajit"
branches:
  only:
  - master
install:
- sudo apt-get install luajit luarocks
- sudo luarocks install lpeg
- sudo luarocks install luafilesystem
- sudo luarocks install busted 1.11.1
script: busted spec
notifications:
  slack:
    secure: GWQZ2CUaBYUZTTHXCkSG7A3L8kRJsHRfkAHZ0+V1RAFzcxb7eCCizMaRHSnRXM/YTaCvGORWYSzftLrkqQIk84RSl4Uru5B4cypJ3ArjNFAph+rue00+jbhYdJO8cq5OoLZRal/LCoEnjKO723CVhlScxz8/rSY/eSvaGUJJkb0=
