local doc = require "lastdoc"

describe("the heading parsing stuff", function()
    describe("the parseNode func", function()
        local title = function(str)
            return doc.title(doc.gen(str))
        end

        it("should parse a doc with a normal header", function()
            assert.is.same("lastdoc", title("lastdoc\n=======\n"))
            assert.is.same("lastdoc", title("lastdoc\n======="))
        end)
        it("should parse a doc with a normal header - 1", function()
            assert.is.same("lastdoc", title("lastdoc\n======\n"))
            assert.is.same("lastdoc", title("lastdoc\n======"))
        end)
        it("should parse a doc with a normal header - 2", function()
            assert.is.same("lastdoc", title("lastdoc\n=====\n"))
            assert.is.same("lastdoc", title("lastdoc\n====="))
        end)
        it("should parse a doc with a normal header + 1", function()
            assert.is.same("lastdoc", title("lastdoc\n========\n"))
            assert.is.same("lastdoc", title("lastdoc\n========"))
        end)
        it("should parse a doc with a normal header + 2", function()
            assert.is.same("lastdoc", title("lastdoc\n=========\n"))
            assert.is.same("lastdoc", title("lastdoc\n========="))
        end)

        it("should not parse a doc with a normal header - 3", function()
            assert.is_not.same("lastdoc", title("lastdoc\n====\n"))
            assert.is_not.same("lastdoc", title("lastdoc\n===="))
        end)
        it("should not parse a doc with a normal header + 3", function()
            assert.is_not.same("lastdoc", title("lastdoc\n==========\n"))
            assert.is_not.same("lastdoc", title("lastdoc\n=========="))
        end)

        -- not implemented yet
        pending("should parse a one-line header with no right delim", function()
            assert.is.same("lastdoc", title("= title"))
        end)
        pending("should parse a one-line header with a right delim", function()
            assert.is.same("lastdoc", title("= title ="))
        end)
        pending("should parse a one-line header with no right delim and no left ws", function()
            assert.is.same("lastdoc", title("=title"))
        end)
        pending("should parse a one-line header with a right delim and no left ws", function()
            assert.is.same("lastdoc", title("=title ="))
        end)
    end)
end)
